# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text_editorui.ui'
#
# Created: Wed Oct 23 14:58:49 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(939, 600)
        self.main_title="yayun's notepad"
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 1021, 601))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 939, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHighlight_Mode = QtGui.QMenu(self.menuView)
        self.menuHighlight_Mode.setObjectName(_fromUtf8("menuHighlight_Mode"))
        self.menuScript = QtGui.QMenu(self.menuHighlight_Mode)
        self.menuScript.setObjectName(_fromUtf8("menuScript"))
        self.menuSources = QtGui.QMenu(self.menuHighlight_Mode)
        self.menuSources.setObjectName(_fromUtf8("menuSources"))
        self.menuMarkup = QtGui.QMenu(self.menuHighlight_Mode)
        self.menuMarkup.setObjectName(_fromUtf8("menuMarkup"))
        self.menuSearch = QtGui.QMenu(self.menuBar)
        self.menuSearch.setObjectName(_fromUtf8("menuSearch"))
        self.menuTool = QtGui.QMenu(self.menuBar)
        self.menuTool.setObjectName(_fromUtf8("menuTool"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon/open-file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionNew = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icon/File-New-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.action_Save = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icon/save.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save.setIcon(icon2)
        self.action_Save.setObjectName(_fromUtf8("action_Save"))
        self.action_Saveas = QtGui.QAction(MainWindow)
        self.action_Saveas.setObjectName(_fromUtf8("action_Saveas"))
        self.actionPrint = QtGui.QAction(MainWindow)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionPrint_Preview = QtGui.QAction(MainWindow)
        self.actionPrint_Preview.setObjectName(_fromUtf8("actionPrint_Preview"))
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.action_quit = QtGui.QAction(MainWindow)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionCut = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icon/cut.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon3)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionSelect_All = QtGui.QAction(MainWindow)
        self.actionSelect_All.setObjectName(_fromUtf8("actionSelect_All"))
        self.actionInsert = QtGui.QAction(MainWindow)
        self.actionInsert.setObjectName(_fromUtf8("actionInsert"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionToolbar = QtGui.QAction(MainWindow)
        self.actionToolbar.setObjectName(_fromUtf8("actionToolbar"))
        self.actionStatusbar = QtGui.QAction(MainWindow)
        self.actionStatusbar.setObjectName(_fromUtf8("actionStatusbar"))
        self.actionSidebar = QtGui.QAction(MainWindow)
        self.actionSidebar.setObjectName(_fromUtf8("actionSidebar"))
        self.actionBottom_Panel = QtGui.QAction(MainWindow)
        self.actionBottom_Panel.setObjectName(_fromUtf8("actionBottom_Panel"))
        self.actionFullscreen = QtGui.QAction(MainWindow)
        self.actionFullscreen.setObjectName(_fromUtf8("actionFullscreen"))
        self.actionPlainText = QtGui.QAction(MainWindow)
        self.actionPlainText.setObjectName(_fromUtf8("actionPlainText"))
        self.actionCss = QtGui.QAction(MainWindow)
        self.actionCss.setObjectName(_fromUtf8("actionCss"))
        self.actionRuby = QtGui.QAction(MainWindow)
        self.actionRuby.setObjectName(_fromUtf8("actionRuby"))
        self.actionJavascript = QtGui.QAction(MainWindow)
        self.actionJavascript.setObjectName(_fromUtf8("actionJavascript"))
        self.actionC = QtGui.QAction(MainWindow)
        self.actionC.setObjectName(_fromUtf8("actionC"))
        self.actionC_sharp = QtGui.QAction(MainWindow)
        self.actionC_sharp.setObjectName(_fromUtf8("actionC_sharp"))
        self.actionC_plus_plus = QtGui.QAction(MainWindow)
        self.actionC_plus_plus.setObjectName(_fromUtf8("actionC_plus_plus"))
        self.actionJava = QtGui.QAction(MainWindow)
        self.actionJava.setObjectName(_fromUtf8("actionJava"))
        self.actionHtml = QtGui.QAction(MainWindow)
        self.actionHtml.setObjectName(_fromUtf8("actionHtml"))
        self.actionMarkdown = QtGui.QAction(MainWindow)
        self.actionMarkdown.setObjectName(_fromUtf8("actionMarkdown"))
        self.actionLisp = QtGui.QAction(MainWindow)
        self.actionLisp.setObjectName(_fromUtf8("actionLisp"))
        self.actionHaskell = QtGui.QAction(MainWindow)
        self.actionHaskell.setObjectName(_fromUtf8("actionHaskell"))
        self.actionObject_C = QtGui.QAction(MainWindow)
        self.actionObject_C.setObjectName(_fromUtf8("actionObject_C"))
        self.actionGo = QtGui.QAction(MainWindow)
        self.actionGo.setObjectName(_fromUtf8("actionGo"))
        self.actionVB_net = QtGui.QAction(MainWindow)
        self.actionVB_net.setObjectName(_fromUtf8("actionVB_net"))
        self.actionFind = QtGui.QAction(MainWindow)
        self.actionFind.setObjectName(_fromUtf8("actionFind"))
        self.actionFind_next = QtGui.QAction(MainWindow)
        self.actionFind_next.setObjectName(_fromUtf8("actionFind_next"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_Saveas)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionPrint_Preview)
        self.menuFile.addAction(self.action_Close)
        self.menuFile.addAction(self.action_quit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addAction(self.actionInsert)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuScript.addAction(self.actionCss)
        self.menuScript.addAction(self.actionRuby)
        self.menuScript.addAction(self.actionJavascript)
        self.menuSources.addAction(self.actionC)
        self.menuSources.addAction(self.actionC_sharp)
        self.menuSources.addAction(self.actionC_plus_plus)
        self.menuSources.addAction(self.actionJava)
        self.menuSources.addAction(self.actionLisp)
        self.menuSources.addAction(self.actionHaskell)
        self.menuSources.addAction(self.actionObject_C)
        self.menuSources.addAction(self.actionGo)
        self.menuSources.addAction(self.actionVB_net)
        self.menuMarkup.addAction(self.actionHtml)
        self.menuMarkup.addAction(self.actionMarkdown)
        self.menuHighlight_Mode.addAction(self.actionPlainText)
        self.menuHighlight_Mode.addAction(self.menuScript.menuAction())
        self.menuHighlight_Mode.addAction(self.menuSources.menuAction())
        self.menuHighlight_Mode.addAction(self.menuMarkup.menuAction())
        self.menuView.addAction(self.actionToolbar)
        self.menuView.addAction(self.actionStatusbar)
        self.menuView.addAction(self.actionSidebar)
        self.menuView.addAction(self.actionBottom_Panel)
        self.menuView.addAction(self.actionFullscreen)
        self.menuView.addAction(self.menuHighlight_Mode.menuAction())
        self.menuSearch.addAction(self.actionFind)
        self.menuSearch.addAction(self.actionFind_next)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuSearch.menuAction())
        self.menuBar.addAction(self.menuTool.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar_2.addAction(self.actionNew)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.actionOpen)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.action_Save)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.actionCut)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow",self.main_title, None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHighlight_Mode.setTitle(QtGui.QApplication.translate("MainWindow", "Highlight Mode ", None, QtGui.QApplication.UnicodeUTF8))
        self.menuScript.setTitle(QtGui.QApplication.translate("MainWindow", "Script", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSources.setTitle(QtGui.QApplication.translate("MainWindow", "Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMarkup.setTitle(QtGui.QApplication.translate("MainWindow", "Markup", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSearch.setTitle(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTool.setTitle(QtGui.QApplication.translate("MainWindow", "Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setIconText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Saveas.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("MainWindow", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint_Preview.setText(QtGui.QApplication.translate("MainWindow", "Print Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.action_quit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("MainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("MainWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("MainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInsert.setText(QtGui.QApplication.translate("MainWindow", "Insert Date and Time", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToolbar.setText(QtGui.QApplication.translate("MainWindow", "Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStatusbar.setText(QtGui.QApplication.translate("MainWindow", "Statusbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSidebar.setText(QtGui.QApplication.translate("MainWindow", "Sidebar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBottom_Panel.setText(QtGui.QApplication.translate("MainWindow", "Bottom Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullscreen.setText(QtGui.QApplication.translate("MainWindow", "Fullscreen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlainText.setText(QtGui.QApplication.translate("MainWindow", "PlainText", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCss.setText(QtGui.QApplication.translate("MainWindow", "Python", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRuby.setText(QtGui.QApplication.translate("MainWindow", "Ruby", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJavascript.setText(QtGui.QApplication.translate("MainWindow", "Javascript", None, QtGui.QApplication.UnicodeUTF8))
        self.actionC.setText(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionC_sharp.setText(QtGui.QApplication.translate("MainWindow", "C#", None, QtGui.QApplication.UnicodeUTF8))
        self.actionC_plus_plus.setText(QtGui.QApplication.translate("MainWindow", "C++", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJava.setText(QtGui.QApplication.translate("MainWindow", "Java", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHtml.setText(QtGui.QApplication.translate("MainWindow", "Html", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMarkdown.setText(QtGui.QApplication.translate("MainWindow", "Markdown", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLisp.setText(QtGui.QApplication.translate("MainWindow", "Lisp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHaskell.setText(QtGui.QApplication.translate("MainWindow", "Haskell", None, QtGui.QApplication.UnicodeUTF8))
        self.actionObject_C.setText(QtGui.QApplication.translate("MainWindow", "Object-C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGo.setText(QtGui.QApplication.translate("MainWindow", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVB_net.setText(QtGui.QApplication.translate("MainWindow", "VB,net", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setText(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind_next.setText(QtGui.QApplication.translate("MainWindow", "Find next", None, QtGui.QApplication.UnicodeUTF8))

